[server]
runOnSave = true        # auto-rerun when any watched file is saved
fileWatcherType = "auto"  # (default) use watchdog if available
# change primary colour 

[theme]
base="dark"
primaryColor="#229dc7"
